name: 'Get Target Platforms of Flutter Project'
description: 'Get Target Platforms of Your Flutter Project from the pubspec File.'
author: 'Ali Fadaei'
inputs:
  pubspec-path:
    description: 'The pubspec.yaml file path. Optional. Default: `pubspec.yaml`'
    default: 'pubspec.yaml'
outputs:
  name: 
    description: "your Flutter project name"
  android: 
    description: "your Flutter project should Release on android platform"
  ios: 
    description: "your Flutter project should Release on ios platform"
  web: 
    description: "your Flutter project should Release on web platform"
  windows: 
    description: "your Flutter project should Release on windows platform"
  linux: 
    description: "your Flutter project should Release on linux platform"
  macos: 
    description: "your Flutter project should Release on macos platform"

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'package'
  color: 'cyan'
