name: 'Get Target Platforms from pubspec.yaml'
description: 'Get Target Platforms of Your Flutter Project from the pubspec File.'
author: 'Ali Fadaei'
inputs:
  pubspec_path:
    description: 'The pubspec.yaml file path. Optional. Default: `pubspec.yaml`'
    default: 'pubspec.yaml'
  custom_key:
    description: 'a custom key for retrive from pubspec.yaml file'
    required: false

outputs:
  name: 
    description: "your Flutter project name"
  android: 
    description: "your Flutter project should Release on android platform"
  ios: 
    description: "your Flutter project should Release on ios platform"
  web: 
    description: "your Flutter project should Release on web platform"
  windows: 
    description: "your Flutter project should Release on windows platform"
  linux: 
    description: "your Flutter project should Release on linux platform"
  macos: 
    description: "your Flutter project should Release on macos platform"
  custom_value:
    description: 'value of the custom key retrived from pubspec.yaml file'


runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'zap'
  color: 'blue'
